/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase11;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.EventObject;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class CampoTextoMarc extends javax.swing.JFrame {

    /**
     * Creates new form CampoTextoMarc
     */
    public CampoTextoMarc() {
        initComponents();
        ManejadorCampoTexto manejador = new ManejadorCampoTexto();
        tfCampoTexto1.addActionListener(manejador);
        tfCampoTexto2.addActionListener(manejador);
        tfCampoTexto3.addActionListener(manejador);
        pfCampoContrasenia.addActionListener(manejador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfCampoTexto1 = new javax.swing.JTextField();
        tfCampoTexto2 = new javax.swing.JTextField();
        tfCampoTexto3 = new javax.swing.JTextField();
        pfCampoContrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfCampoTexto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampoTexto1ActionPerformed(evt);
            }
        });

        tfCampoTexto2.setText("Escriba el texto aqui");
        tfCampoTexto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampoTexto2ActionPerformed(evt);
            }
        });

        tfCampoTexto3.setEditable(false);
        tfCampoTexto3.setText("Campo de texto no editable");
        tfCampoTexto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampoTexto3ActionPerformed(evt);
            }
        });

        pfCampoContrasenia.setText("jPasswordField1");
        pfCampoContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfCampoContraseniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCampoTexto1)
                    .addComponent(tfCampoTexto2)
                    .addComponent(tfCampoTexto3)
                    .addComponent(pfCampoContrasenia))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfCampoTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfCampoTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfCampoTexto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pfCampoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCampoTexto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoTexto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampoTexto1ActionPerformed

    private void tfCampoTexto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoTexto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampoTexto2ActionPerformed

    private void tfCampoTexto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoTexto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampoTexto3ActionPerformed

    private void pfCampoContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfCampoContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfCampoContraseniaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField pfCampoContrasenia;
    private javax.swing.JTextField tfCampoTexto1;
    private javax.swing.JTextField tfCampoTexto2;
    private javax.swing.JTextField tfCampoTexto3;
    // End of variables declaration//GEN-END:variables

    private class ManejadorCampoTexto implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent evento) {
            String cadena = " ";

            if (evento.getSource() == tfCampoTexto1) {
                cadena = String.format("campoTexto1: %s", evento.getActionCommand());
            } else if (evento.getSource() == tfCampoTexto2) {
                cadena = String.format("campoTexto2: %s", tfCampoTexto2.getText());
            } else if (evento.getSource() == tfCampoTexto3) {
                cadena = String.format("campoTexto3: %s", evento.getActionCommand());
            } else if (evento.getSource() == pfCampoContrasenia) {
                cadena = String.format("pfCampoContrasenia: %s", new String(pfCampoContrasenia.getPassword()));
            }
            
            JOptionPane.showMessageDialog(null, cadena);
        }

    }
}
