/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase11;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class Temperatura extends javax.swing.JFrame {

    protected Double Salida;
      protected String SalidaString;
    
    /**
     * Creates new form Temperatura
     */
    public Temperatura() {
        initComponents();
        
        
        
        ManejarBoton manejadorBoton = new ManejarBoton();
        bConvertir.addActionListener(manejadorBoton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rbCentigrado = new javax.swing.JRadioButton();
        rbFa = new javax.swing.JRadioButton();
        rbKelvin = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        cbSalida = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        tfCuadroTexto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bConvertir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mConvertidor = new javax.swing.JMenu();
        mEntrada = new javax.swing.JMenu();
        rbmCentigrados = new javax.swing.JRadioButtonMenuItem();
        rbmFa = new javax.swing.JRadioButtonMenuItem();
        rbmKelvin = new javax.swing.JRadioButtonMenuItem();
        mSalida = new javax.swing.JMenu();
        rbmScentigrados = new javax.swing.JRadioButtonMenuItem();
        rbmSfa = new javax.swing.JRadioButtonMenuItem();
        rbmSkelvin = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Convertidor "));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada"));

        buttonGroup1.add(rbCentigrado);
        rbCentigrado.setText("Centígrados");

        buttonGroup1.add(rbFa);
        rbFa.setText("Fahrenheit");

        buttonGroup1.add(rbKelvin);
        rbKelvin.setText("Kelvin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rbFa)
            .addComponent(rbKelvin)
            .addComponent(rbCentigrado)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCentigrado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbKelvin)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Salida"));

        cbSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centígrados", "Fahrenheit", "Kelvin" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(cbSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cbSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura"));

        tfCuadroTexto.setText("0");

        jLabel1.setText("Resultado");

        bConvertir.setText("Convertir");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tfCuadroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(bConvertir))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCuadroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bConvertir)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jMenu1.setMnemonic('a');
        jMenu1.setText("Archivo");

        jMenuItem1.setMnemonic('s');
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        mConvertidor.setMnemonic('c');
        mConvertidor.setText("Convertidor");
        mConvertidor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mConvertidorStateChanged(evt);
            }
        });

        mEntrada.setText("Entrada");

        buttonGroup2.add(rbmCentigrados);
        rbmCentigrados.setSelected(true);
        rbmCentigrados.setText("Centígrados");
        mEntrada.add(rbmCentigrados);

        buttonGroup2.add(rbmFa);
        rbmFa.setText("Fahrenheit");
        mEntrada.add(rbmFa);

        buttonGroup2.add(rbmKelvin);
        rbmKelvin.setText("Kelvin");
        mEntrada.add(rbmKelvin);

        mConvertidor.add(mEntrada);

        mSalida.setText("Salida");

        buttonGroup3.add(rbmScentigrados);
        rbmScentigrados.setSelected(true);
        rbmScentigrados.setText("Centígrados");
        mSalida.add(rbmScentigrados);

        buttonGroup3.add(rbmSfa);
        rbmSfa.setText("Fahrenheit");
        mSalida.add(rbmSfa);

        buttonGroup3.add(rbmSkelvin);
        rbmSkelvin.setText("Kelvin");
        mSalida.add(rbmSkelvin);

        mConvertidor.add(mSalida);

        jMenuBar1.add(mConvertidor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mConvertidorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mConvertidorStateChanged
       if (rbCentigrado.isSelected() && cbSalida.getSelectedItem()=="Fahrenheit") {
               rbmCentigrados.setSelected(true);
               rbmSfa.setSelected(true);
            }else if (rbCentigrado.isSelected() && cbSalida.getSelectedItem()=="Kelvin") {
                rbmCentigrados.setSelected(true);
                rbmSkelvin.setSelected(true);
            }else if (rbFa.isSelected() && "Centígrados"==cbSalida.getSelectedItem()) {
                rbmFa.setSelected(true);
                rbmScentigrados.setSelected(true);
            }else if (rbFa.isSelected() && cbSalida.getSelectedItem()=="Kelvin") {
                rbmFa.setSelected(true);
                rbmSkelvin.setSelected(true);
            }else if (rbKelvin.isSelected() && cbSalida.getSelectedItem()=="Centígrados") {
               rbmKelvin.setSelected(true);
               rbmScentigrados.setSelected(true);
            }else if (rbKelvin.isSelected() && cbSalida.getSelectedItem()=="Fahrenheit") {
               rbmKelvin.setSelected(true);
               rbmSfa.setSelected(true);
            }
    }//GEN-LAST:event_mConvertidorStateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConvertir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenu mConvertidor;
    private javax.swing.JMenu mEntrada;
    private javax.swing.JMenu mSalida;
    private javax.swing.JRadioButton rbCentigrado;
    private javax.swing.JRadioButton rbFa;
    private javax.swing.JRadioButton rbKelvin;
    private javax.swing.JRadioButtonMenuItem rbmCentigrados;
    private javax.swing.JRadioButtonMenuItem rbmFa;
    private javax.swing.JRadioButtonMenuItem rbmKelvin;
    private javax.swing.JRadioButtonMenuItem rbmScentigrados;
    private javax.swing.JRadioButtonMenuItem rbmSfa;
    private javax.swing.JRadioButtonMenuItem rbmSkelvin;
    private javax.swing.JTextField tfCuadroTexto;
    // End of variables declaration//GEN-END:variables

public class ManejarBoton implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Salida = Double.parseDouble(tfCuadroTexto.getText());
            
            if (rbCentigrado.isSelected() && cbSalida.getSelectedItem()=="Fahrenheit") {
                Salida = (Salida* 9/5) + 32;
                SalidaString = String.valueOf(Salida)+ " F";
                //Selecciones del menu
               rbmCentigrados.setSelected(true);
               rbmSfa.setSelected(true);

            }else if (rbCentigrado.isSelected() && cbSalida.getSelectedItem()=="Kelvin") {
                Salida = Salida + 273.15;
                 SalidaString = String.valueOf(Salida)+ " K";
               
            }else if (rbFa.isSelected() && "Centígrados"==cbSalida.getSelectedItem()) {
                Salida = (Salida -32) * 5/9  ;
                SalidaString = String.valueOf(Salida)+ " °C";
            
            }else if (rbFa.isSelected() && cbSalida.getSelectedItem()=="Kelvin") {
                 Salida = (Salida -32) * 5/9 + 273.15 ; 
                 SalidaString = String.valueOf(Salida)+ " K";
                
            }else if (rbKelvin.isSelected() && cbSalida.getSelectedItem()=="Centígrados") {
                Salida = Salida - 273.15;
                SalidaString = String.valueOf(Salida)+ " °C";
              
            }else if (rbKelvin.isSelected() && cbSalida.getSelectedItem()=="Fahrenheit") {
                Salida = (Salida -273.15) * 9/5 + 32;
                SalidaString = String.valueOf(Salida)+ " F";
             

            }
            jLabel1.setText(SalidaString);
            
        }

        
}

}
